complete -c neet -f -o d -l debug -d 'print debug info and exit'
complete -c neet -f -o e -l edit -d 'edit list'
complete -c neet -f -o l -l location -d 'print location and exit'
complete -c neet -f -o n -l next -d 'set and play next episode'
complete -c neet -f -o p -l previous -d 'set and play previous episode'
complete -c neet -f -o s -l set -d 'set and play specified episode'
complete -c neet -f -o h -l help -d 'print help and exit'
