complete -c neet -f -o d -l debug -d 'Print debug info and exit'
complete -c neet -f -o e -l edit -d 'Edit list'
complete -c neet -f -o l -l location -d 'Print location and exit'
complete -c neet -f -o n -l next -d 'Set and play next episode'
complete -c neet -f -o p -l previous -d 'Set and play previous episode'
complete -c neet -f -o s -l set -d 'Set and play specified episode'
complete -c neet -f -o h -l help -d 'Print help and exit'
